name: DEV Deployment for Android Action

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build_apk:
    runs-on: macos-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: "stable"

      - name: Install Android Gems
        working-directory: ${{ github.workspace }}/android
        run: bundle install

      - name: Flutter clean
        working-directory: ${{ github.workspace }}
        run: flutter clean

      - name: Flutter get
        working-directory: ${{ github.workspace }}
        run: flutter pub get

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > ${{ github.workspace }}/android/keystore.jks

      - name: Setup key.properties
        working-directory: ${{ github.workspace }}
        run: |
          echo keyPassword=\${{ secrets.SIGNING_STORE_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.SIGNING_KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.SIGNING_KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
        env:
          PROPERTIES_PATH: "${{ github.workspace }}/android/key.properties"

      - name: Setup local.properties
        working-directory: ${{ github.workspace }}
        run: |
          echo flutter.compileSdkVersion=33 > ${{env.PROPERTIES_PATH}}
          echo flutter.minSdkVersion=23 > ${{env.PROPERTIES_PATH}}
        env:
          PROPERTIES_PATH: "${{ github.workspace }}/android/local.properties"

      - name: Flutter Generate Section
        working-directory: ${{ github.workspace }}
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      # Setup environment
      - name: Setup ENV
        working-directory: ${{ github.workspace }}
        run: |
          touch .env
          echo BASE_URL=https://dummyjson.com >> .env
          cat .env

      - name: Build APK
        working-directory: ${{ github.workspace }}
        run: flutter build apk -t lib/main_dev.dart --flavor dev --release

      - name: Create Firebase Service Credentials file
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
          base64 -d -i firebase_credentials.json.b64 > "${{ github.workspace }}/android/firebase_credentials.json"
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Distribute Android Beta App
        working-directory: ${{ github.workspace }}/android
        run: bundle exec fastlane distribute_android_app
        env:
          FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          ANDROID_APK_PATH: "../build/app/outputs/flutter-apk/app-dev-release.apk"